// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TestVCE.Models;

public partial class Address
{
    public Guid Oid { get; set; }

    public string? Street { get; set; }

    public string? City { get; set; }

    public string? StateProvince { get; set; }

    public string? ZipPostal { get; set; }

    public Guid? Country { get; set; }

    public int? OptimisticLockField { get; set; }

    public int? Gcrecord { get; set; }

    public virtual Country? CountryNavigation { get; set; }

    public virtual ICollection<Party> PartyAddress1Navigations { get; set; } = new List<Party>();

    public virtual ICollection<Party> PartyAddress2Navigations { get; set; } = new List<Party>();
}