// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TestVCE.Models;

public partial class ApplicationUserRolePermission
{
    public int Oid { get; set; }

    public Guid? ApplicationUser { get; set; }

    public string? ApplicationRoleCode { get; set; }

    public string? ApplicationRoleName { get; set; }

    public string? PermissionDataTypeName { get; set; }

    public string? PermissionDisplayValue { get; set; }

    public string? PermissionValue { get; set; }

    public int? OptimisticLockField { get; set; }

    public int? Gcrecord { get; set; }

    public virtual ApplicationUser? ApplicationUserNavigation { get; set; }
}