// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TestVCE.Models;

public partial class ApplicationUser
{
    public Guid Oid { get; set; }

    public virtual ICollection<AdministratorProfile> AdministratorProfiles { get; set; } = new List<AdministratorProfile>();

    public virtual ICollection<ApplicationUserRolePermission> ApplicationUserRolePermissions { get; set; } = new List<ApplicationUserRolePermission>();

    public virtual ICollection<EmployerProfile> EmployerProfileApplicationUserNavigations { get; set; } = new List<EmployerProfile>();

    public virtual ICollection<EmployerProfile> EmployerProfileSchoolPartnerOfficerApplicationUserNavigations { get; set; } = new List<EmployerProfile>();

    public virtual PermissionPolicyUser OidNavigation { get; set; } = null!;

    public virtual ICollection<SchoolEmployeeProfile> SchoolEmployeeProfiles { get; set; } = new List<SchoolEmployeeProfile>();

    public virtual ICollection<Student> Students { get; set; } = new List<Student>();
}