// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TestVCE.Models;

public partial class Audit
{
    public int Oid { get; set; }

    public string? User { get; set; }

    public DateTime? Date { get; set; }

    public int? Action { get; set; }

    public string? ActionName { get; set; }

    public string? AuditedRecord { get; set; }

    public string? TableName { get; set; }

    public string? RecordOid { get; set; }

    public int? OptimisticLockField { get; set; }

    public int? Gcrecord { get; set; }

    public virtual ICollection<ModificationInfo> ModificationInfos { get; set; } = new List<ModificationInfo>();
}