// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TestVCE.Models;

public partial class CertificateType
{
    public int Oid { get; set; }

    public string? Code { get; set; }

    public string? NameTh { get; set; }

    public string? NameEng { get; set; }

    public int? OptimisticLockField { get; set; }

    public int? Gcrecord { get; set; }

    public virtual ICollection<JobPosting> JobPostings { get; set; } = new List<JobPosting>();

    public virtual ICollection<StudentVeceducationInformation> StudentVeceducationInformations { get; set; } = new List<StudentVeceducationInformation>();

    public virtual ICollection<Student> Students { get; set; } = new List<Student>();
}