// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TestVCE.Models;

public partial class Corporate
{
    public int Oid { get; set; }

    public string? Taxid { get; set; }

    public string? Name { get; set; }

    public int? Province { get; set; }

    public int? OptimisticLockField { get; set; }

    public int? Gcrecord { get; set; }

    public virtual Province? ProvinceNavigation { get; set; }
}