// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TestVCE.Models;

public partial class Country
{
    public Guid Oid { get; set; }

    public string? Name { get; set; }

    public string? PhoneCode { get; set; }

    public int? OptimisticLockField { get; set; }

    public int? Gcrecord { get; set; }

    public virtual ICollection<Address> Addresses { get; set; } = new List<Address>();
}