// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TestVCE.Models;

public partial class Curriculum
{
    public int Oid { get; set; }

    public string? CuriculumType { get; set; }

    public string? CurriculumId { get; set; }

    public string? CurriculumYear { get; set; }

    public string? DegreeLevelCode { get; set; }

    public string? DegreeLevelId { get; set; }

    public string? MajorCode { get; set; }

    public string? MajorId { get; set; }

    public string? MinorCode { get; set; }

    public string? MinorId { get; set; }

    public string? Remark { get; set; }

    public string? StructureYearId { get; set; }

    public string? SubjectTypeCode { get; set; }

    public string? SubjectTypeId { get; set; }

    public string? Year { get; set; }

    public int? QuantityOfRelatedIndustry { get; set; }

    public int? QuantityOfRelatedJobPosition { get; set; }

    public int? OptimisticLockField { get; set; }

    public int? Gcrecord { get; set; }
}