// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TestVCE.Models;

public partial class EmployerFileAttachment
{
    public int Oid { get; set; }

    public int? Fileattachment { get; set; }

    public int? EmployerProfile { get; set; }

    public int? OptimisticLockField { get; set; }

    public int? Gcrecord { get; set; }

    public virtual EmployerProfile? EmployerProfileNavigation { get; set; }

    public virtual FileAttachment? FileattachmentNavigation { get; set; }
}