// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TestVCE.Models;

public partial class EmployerSummary
{
    public int Oid { get; set; }

    public string? IdentityId { get; set; }

    public string? NameTh { get; set; }

    public string? BranchNo { get; set; }

    public string? Address { get; set; }

    public string? ProvinceCode { get; set; }

    public string? ProvinceName { get; set; }

    public string? Zipcode { get; set; }

    public int? OptimisticLockField { get; set; }

    public int? Gcrecord { get; set; }

    public bool? DontKnowIdentityId { get; set; }
}