// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TestVCE.Models;

public partial class EmployerSchoolContact
{
    public int Oid { get; set; }

    public int? EmployerProfile { get; set; }

    public int? School { get; set; }

    public string? FullName { get; set; }

    public string? Phone { get; set; }

    public int? OptimisticLockField { get; set; }

    public int? Gcrecord { get; set; }

    public virtual EmployerProfile? EmployerProfileNavigation { get; set; }

    public virtual School? SchoolNavigation { get; set; }
}