// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TestVCE.Models;

public partial class EmployerProfile
{
    public int Oid { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? LastUpdatedDate { get; set; }

    public DateTime? DeletedDate { get; set; }

    public int? EmployerProfileStatus { get; set; }

    public int? EmployerProfileType { get; set; }

    public string? IdentityId { get; set; }

    public string? NameTh { get; set; }

    public int? EmployerMainBusinessType { get; set; }

    public int? BusinessType { get; set; }

    public string? Description { get; set; }

    public string? BenefitDescription { get; set; }

    public string? EmployerProfilePhotoBase64 { get; set; }

    public string? SocialSecurityNumber { get; set; }

    public string? Email { get; set; }

    public bool? IsEmailVerified { get; set; }

    public DateTime? EmailVerifiedDate { get; set; }

    public string? WebSiteUrl { get; set; }

    public bool? IsRequiredJobApplicantToRegisterThemSelfOrViaPost { get; set; }

    public bool? IsOpenForOnlineApplicant { get; set; }

    public string? AddressNo { get; set; }

    public int? Province { get; set; }

    public int? District { get; set; }

    public int? Tambon { get; set; }

    public string? LocationPhotoBase64 { get; set; }

    public string? LogoPhotoBase64 { get; set; }

    public string? Phone { get; set; }

    public string? Fax { get; set; }

    public string? LocationLatitude { get; set; }

    public string? LocationLongtitude { get; set; }

    public string? CoordinatorEmail { get; set; }

    public int? CoordinatorTitleName { get; set; }

    public string? CoordinatorFirstName { get; set; }

    public string? CoordinatorLastName { get; set; }

    public string? CoordinatorPhone { get; set; }

    public string? CoordinatorPositionName { get; set; }

    public string? CoordinatorFax { get; set; }

    public Guid? ApplicationUser { get; set; }

    public int? SchoolPartnerOfficerSchool { get; set; }

    public Guid? SchoolPartnerOfficerApplicationUser { get; set; }

    public int? CompletionPercentage { get; set; }

    public int? OptimisticLockField { get; set; }

    public int? Gcrecord { get; set; }

    public virtual ApplicationUser? ApplicationUserNavigation { get; set; }

    public virtual EmployerBusinessType? BusinessTypeNavigation { get; set; }

    public virtual TitleName? CoordinatorTitleNameNavigation { get; set; }

    public virtual District? DistrictNavigation { get; set; }

    public virtual ICollection<EmployerFileAttachment> EmployerFileAttachments { get; set; } = new List<EmployerFileAttachment>();

    public virtual EmployerMainBusinessType? EmployerMainBusinessTypeNavigation { get; set; }

    public virtual EmployerProfileStatus? EmployerProfileStatusNavigation { get; set; }

    public virtual EmployerProfileType? EmployerProfileTypeNavigation { get; set; }

    public virtual ICollection<EmployerSchoolContact> EmployerSchoolContacts { get; set; } = new List<EmployerSchoolContact>();

    public virtual ICollection<JobPosting> JobPostings { get; set; } = new List<JobPosting>();

    public virtual Province? ProvinceNavigation { get; set; }

    public virtual ApplicationUser? SchoolPartnerOfficerApplicationUserNavigation { get; set; }

    public virtual School? SchoolPartnerOfficerSchoolNavigation { get; set; }

    public virtual Tambon? TambonNavigation { get; set; }
}