// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TestVCE.Models;

public partial class EntityStatus
{
    public int Oid { get; set; }

    public string? StatusGroupName { get; set; }

    public string? StatusCode { get; set; }

    public string? StatusName { get; set; }

    public string? Description { get; set; }

    public int? OptimisticLockField { get; set; }

    public int? Gcrecord { get; set; }

    public virtual ICollection<GraduatedStudentJobTrackingReport> GraduatedStudentJobTrackingReportImportStudentDataStatusNavigations { get; set; } = new List<GraduatedStudentJobTrackingReport>();

    public virtual ICollection<GraduatedStudentJobTrackingReport> GraduatedStudentJobTrackingReportJobTrackingStatusNavigations { get; set; } = new List<GraduatedStudentJobTrackingReport>();

    public virtual ICollection<GraduatedStudentJobTrackingReportMain> GraduatedStudentJobTrackingReportMainImportStudentDataStatusNavigations { get; set; } = new List<GraduatedStudentJobTrackingReportMain>();

    public virtual ICollection<GraduatedStudentJobTrackingReportMain> GraduatedStudentJobTrackingReportMainJobTrackingStatusNavigations { get; set; } = new List<GraduatedStudentJobTrackingReportMain>();

    public virtual ICollection<JobApplication> JobApplications { get; set; } = new List<JobApplication>();

    public virtual ICollection<JobPosting> JobPostings { get; set; } = new List<JobPosting>();
}