// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TestVCE.Models;

public partial class Event
{
    public Guid Oid { get; set; }

    public string? ResourceIds { get; set; }

    public Guid? RecurrencePattern { get; set; }

    public string? Subject { get; set; }

    public string? Description { get; set; }

    public DateTime? StartOn { get; set; }

    public DateTime? EndOn { get; set; }

    public bool? AllDay { get; set; }

    public string? Location { get; set; }

    public int? Label { get; set; }

    public int? Status { get; set; }

    public int? Type { get; set; }

    public double? RemindIn { get; set; }

    public string? ReminderInfoXml { get; set; }

    public DateTime? AlarmTime { get; set; }

    public bool? IsPostponed { get; set; }

    public string? RecurrenceInfoXml { get; set; }

    public int? OptimisticLockField { get; set; }

    public int? Gcrecord { get; set; }

    public virtual ICollection<Event> InverseRecurrencePatternNavigation { get; set; } = new List<Event>();

    public virtual Event? RecurrencePatternNavigation { get; set; }

    public virtual ICollection<ResourceResourcesEventEvent> ResourceResourcesEventEvents { get; set; } = new List<ResourceResourcesEventEvent>();
}