// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TestVCE.Models;

public partial class GraduatedStudentJobTrackingReport
{
    public int Oid { get; set; }

    public int? GraduatedStudentJobTrackingReportMain { get; set; }

    public int? School { get; set; }

    public string? SchoolId { get; set; }

    public string? SchoolName { get; set; }

    public string? SchoolProvinceName { get; set; }

    public string? TargetGraduatedYearTh { get; set; }

    public int? RoundNumber { get; set; }

    public DateTime? TrackingStartDate { get; set; }

    public DateTime? TrackingEndDate { get; set; }

    public int? QuantityOfGraduatedStudentJobTrackingReportStudentDetails { get; set; }

    public int? ImportStudentDataStatus { get; set; }

    public DateTime? ImportStudentDataStatusUpdatedDate { get; set; }

    public int? JobTrackingStatus { get; set; }

    public DateTime? JobTrackingStatusUpdatedDate { get; set; }

    public bool? IsCertified { get; set; }

    public string? CertifierName { get; set; }

    public int? VerifyManager { get; set; }

    public int? CountStudentJobTracked { get; set; }

    public int? SenderToConfirm { get; set; }

    public int? SenderToComplete { get; set; }

    public DateTime? CertifiedDate { get; set; }

    public int? OptimisticLockField { get; set; }

    public int? Gcrecord { get; set; }

    public virtual ICollection<GraduatedStudentJobTrackingReportActivity> GraduatedStudentJobTrackingReportActivities { get; set; } = new List<GraduatedStudentJobTrackingReportActivity>();

    public virtual GraduatedStudentJobTrackingReportMain? GraduatedStudentJobTrackingReportMainNavigation { get; set; }

    public virtual ICollection<GraduatedStudentJobTrackingReportStudentDetail> GraduatedStudentJobTrackingReportStudentDetails { get; set; } = new List<GraduatedStudentJobTrackingReportStudentDetail>();

    public virtual EntityStatus? ImportStudentDataStatusNavigation { get; set; }

    public virtual EntityStatus? JobTrackingStatusNavigation { get; set; }

    public virtual School? SchoolNavigation { get; set; }

    public virtual SchoolEmployeeProfile? SenderToCompleteNavigation { get; set; }

    public virtual SchoolEmployeeProfile? SenderToConfirmNavigation { get; set; }

    public virtual VerifyManager? VerifyManagerNavigation { get; set; }
}