// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TestVCE.Models;

public partial class GraduatedStudent
{
    public int Oid { get; set; }

    public int? SchoolGraduatedStudent { get; set; }

    public string? GraduatedYearTh { get; set; }

    public string? GraduatedSemesters { get; set; }

    public string? SchoolCode { get; set; }

    public string? StudentId { get; set; }

    public string? PrefixId { get; set; }

    public string? Idcard { get; set; }

    public string? Firstname { get; set; }

    public string? Surname { get; set; }

    public string? SchoolName { get; set; }

    public string? StudentCode { get; set; }

    public string? Middlename { get; set; }

    public string? Gender { get; set; }

    public string? FirstnameEn { get; set; }

    public string? SurnameEn { get; set; }

    public string? Nickname { get; set; }

    public DateTime? Birthday { get; set; }

    public string? NationalityId { get; set; }

    public string? RaceId { get; set; }

    public string? ReligionId { get; set; }

    public string? Tel { get; set; }

    public string? Fax { get; set; }

    public string? Email { get; set; }

    public string? GroupCode { get; set; }

    public string? GroupName { get; set; }

    public string? GroupAbbr { get; set; }

    public string? GradeId { get; set; }

    public string? GraduateCode { get; set; }

    public string? GradeNameTh { get; set; }

    public DateTime? EntranceDate { get; set; }

    public string? EntranceYear { get; set; }

    public string? EntranceSemester { get; set; }

    public string? HouseId { get; set; }

    public string? HouseNumber { get; set; }

    public string? Moo { get; set; }

    public string? Soi { get; set; }

    public string? Street { get; set; }

    public string? TumbolCode { get; set; }

    public string? ZipCode { get; set; }

    public string? MajorId { get; set; }

    public string? MajorCode { get; set; }

    public string? MajorNameTh { get; set; }

    public string? MinorId { get; set; }

    public string? MinorCode { get; set; }

    public string? MinorNameTh { get; set; }

    public string? BloodName { get; set; }

    public string? ParentPrefixId { get; set; }

    public string? ParentFirstname { get; set; }

    public string? ParentSurname { get; set; }

    public string? ParentRelation { get; set; }

    public string? ParentPhone { get; set; }

    public string? Gpax { get; set; }

    public DateTime? GraduateDate { get; set; }

    public string? StudentStatusCode { get; set; }

    public string? StudentStatusName { get; set; }

    public string? StudentTypeCode { get; set; }

    public string? StudentTypeName { get; set; }

    public string? EmploymentStatusName { get; set; }

    public string? EditDateEmploymentStatus { get; set; }

    public int? OptimisticLockField { get; set; }

    public int? Gcrecord { get; set; }

    public virtual SchoolGraduatedStudent? SchoolGraduatedStudentNavigation { get; set; }
}