// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TestVCE.Models;

public partial class GraduatedStudentJobTrackingReportActivity
{
    public int Oid { get; set; }

    public int? GraduatedStudentJobTrackingReport { get; set; }

    public DateTime? Date { get; set; }

    public int? Activity { get; set; }

    public int? OptimisticLockField { get; set; }

    public int? Gcrecord { get; set; }

    public virtual JobTrackingReportActivity? ActivityNavigation { get; set; }

    public virtual GraduatedStudentJobTrackingReport? GraduatedStudentJobTrackingReportNavigation { get; set; }
}