// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TestVCE.Models;

public partial class Hcategory
{
    public Guid Oid { get; set; }

    public Guid? Parent { get; set; }

    public string? Name { get; set; }

    public int? OptimisticLockField { get; set; }

    public int? Gcrecord { get; set; }

    public virtual ICollection<Hcategory> InverseParentNavigation { get; set; } = new List<Hcategory>();

    public virtual Hcategory? ParentNavigation { get; set; }
}