// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TestVCE.Models;

public partial class IdgeneratorTable
{
    public Guid Id { get; set; }

    public string? Type { get; set; }

    public string? Prefix { get; set; }

    public int? Oid { get; set; }

    public int? OptimisticLockField { get; set; }
}