// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TestVCE.Models;

public partial class IndustryAndMinorMatching
{
    public int Oid { get; set; }

    public int? Industry { get; set; }

    public int? Minor { get; set; }

    public string? IndustryCode { get; set; }

    public string? IndustryId { get; set; }

    public string? MinorCode { get; set; }

    public string? MinorId { get; set; }

    public int? OptimisticLockField { get; set; }

    public int? Gcrecord { get; set; }

    public virtual Industry? IndustryNavigation { get; set; }

    public virtual Minor? MinorNavigation { get; set; }
}