// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TestVCE.Models;

public partial class Institute
{
    public int Oid { get; set; }

    public string? Email { get; set; }

    public string? Fax { get; set; }

    public string? HouseNumber { get; set; }

    public string? InstituteCode { get; set; }

    public string? InstituteId { get; set; }

    public string? InstituteNameTh { get; set; }

    public string? Soi { get; set; }

    public string? Street { get; set; }

    public string? Telephone { get; set; }

    public string? VillageNumber { get; set; }

    public string? Website { get; set; }

    public string? Zipcode { get; set; }

    public int? OptimisticLockField { get; set; }

    public int? Gcrecord { get; set; }

    public virtual ICollection<School> Schools { get; set; } = new List<School>();
}