// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TestVCE.Models;

public partial class JobPositionMatching
{
    public int Oid { get; set; }

    public string? MajorCode { get; set; }

    public string? MinorCode { get; set; }

    public string? SubjectTypeCode { get; set; }

    public string? PositionName { get; set; }

    public int? OptimisticLockField { get; set; }

    public int? Gcrecord { get; set; }
}