// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TestVCE.Models;

public partial class JobPosition
{
    public int Oid { get; set; }

    public string? Code { get; set; }

    public string? PositionName { get; set; }

    public int? OptimisticLockField { get; set; }

    public int? Gcrecord { get; set; }
}