// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TestVCE.Models;

public partial class JobTrackingReportActivity
{
    public int Oid { get; set; }

    public string? ActivityCode { get; set; }

    public string? ActivityName { get; set; }

    public string? Description { get; set; }

    public int? OptimisticLockField { get; set; }

    public int? Gcrecord { get; set; }

    public virtual ICollection<GraduatedStudentJobTrackingReportActivity> GraduatedStudentJobTrackingReportActivities { get; set; } = new List<GraduatedStudentJobTrackingReportActivity>();
}