// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TestVCE.Models;

public partial class KpiHistoryItem
{
    public Guid Oid { get; set; }

    public Guid? KpiInstance { get; set; }

    public DateTime? RangeStart { get; set; }

    public DateTime? RangeEnd { get; set; }

    public float? Value { get; set; }

    public int? OptimisticLockField { get; set; }

    public virtual KpiInstance? KpiInstanceNavigation { get; set; }
}