// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TestVCE.Models;

public partial class KpiInstance
{
    public Guid Oid { get; set; }

    public DateTime? ForceMeasurementDateTime { get; set; }

    public Guid? KpiDefinition { get; set; }

    public string? Settings { get; set; }

    public int? OptimisticLockField { get; set; }

    public int? Gcrecord { get; set; }

    public virtual KpiDefinition? KpiDefinitionNavigation { get; set; }

    public virtual ICollection<KpiDefinition> KpiDefinitions { get; set; } = new List<KpiDefinition>();

    public virtual ICollection<KpiHistoryItem> KpiHistoryItems { get; set; } = new List<KpiHistoryItem>();

    public virtual ICollection<KpiScorecardScorecardsKpiInstanceIndicator> KpiScorecardScorecardsKpiInstanceIndicators { get; set; } = new List<KpiScorecardScorecardsKpiInstanceIndicator>();
}