// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TestVCE.Models;

public partial class LookingForJob
{
    public int Oid { get; set; }

    public string? Interestedjob1 { get; set; }

    public string? Interestedjob2 { get; set; }

    public string? Interestedjob3 { get; set; }

    public int? Lookingforjobstatus { get; set; }

    public bool? Fulltime { get; set; }

    public bool? Parttime { get; set; }

    public bool? Internship { get; set; }

    public bool? Freelance { get; set; }

    public bool? Byday { get; set; }

    public bool? Temporary { get; set; }

    public bool? Workfromhome { get; set; }

    public string? Rangesalary { get; set; }

    public int? OptimisticLockField { get; set; }

    public int? Gcrecord { get; set; }

    public virtual ICollection<Student> Students { get; set; } = new List<Student>();
}