// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TestVCE.Models;

public partial class Major
{
    public int Oid { get; set; }

    public string? MajorCode { get; set; }

    public string? MajorId { get; set; }

    public string? MajorMoeCode { get; set; }

    public string? MajorNameEn { get; set; }

    public string? MajorNameTh { get; set; }

    public int? OptimisticLockField { get; set; }

    public int? Gcrecord { get; set; }

    public virtual ICollection<StudentVeceducationInformation> StudentVeceducationInformations { get; set; } = new List<StudentVeceducationInformation>();

    public virtual ICollection<Student> Students { get; set; } = new List<Student>();
}