// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TestVCE.Models;

public partial class MediaDataObject
{
    public Guid Oid { get; set; }

    public byte[]? MediaData { get; set; }

    public string? MediaDataKey { get; set; }

    public int? OptimisticLockField { get; set; }

    public int? Gcrecord { get; set; }
}