// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TestVCE.Models;

public partial class Minor
{
    public int Oid { get; set; }

    public string? MinorCode { get; set; }

    public string? MinorId { get; set; }

    public string? MinorMoeCode { get; set; }

    public string? MinorNameEn { get; set; }

    public string? MinorNameTh { get; set; }

    public int? OptimisticLockField { get; set; }

    public int? Gcrecord { get; set; }

    public virtual ICollection<IndustryAndMinorMatching> IndustryAndMinorMatchings { get; set; } = new List<IndustryAndMinorMatching>();

    public virtual ICollection<StudentVeceducationInformation> StudentVeceducationInformations { get; set; } = new List<StudentVeceducationInformation>();

    public virtual ICollection<Student> Students { get; set; } = new List<Student>();
}