// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TestVCE.Models;

public partial class ModelDifference
{
    public Guid Oid { get; set; }

    public string? UserId { get; set; }

    public string? ContextId { get; set; }

    public int? Version { get; set; }

    public int? OptimisticLockField { get; set; }

    public int? Gcrecord { get; set; }

    public virtual ICollection<ModelDifferenceAspect> ModelDifferenceAspects { get; set; } = new List<ModelDifferenceAspect>();
}