// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TestVCE.Models;

public partial class ModuleInfo
{
    public int Id { get; set; }

    public string? Version { get; set; }

    public string? Name { get; set; }

    public string? AssemblyFileName { get; set; }

    public bool? IsMain { get; set; }

    public int? OptimisticLockField { get; set; }
}