// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TestVCE.Models;

public partial class Nationality
{
    public int Oid { get; set; }

    public string? NationalityId { get; set; }

    public string? NationalityTh { get; set; }

    public string? NationalityEng { get; set; }

    public int? OptimisticLockField { get; set; }

    public int? Gcrecord { get; set; }

    public virtual ICollection<Student> Students { get; set; } = new List<Student>();
}