// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TestVCE.Models;

public partial class Note
{
    public Guid Oid { get; set; }

    public string? Author { get; set; }

    public DateTime? DateTime { get; set; }

    public string? Text { get; set; }

    public int? OptimisticLockField { get; set; }

    public int? Gcrecord { get; set; }
}