// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TestVCE.Models;

public partial class NotificationSetup
{
    public int Oid { get; set; }

    public string? NotificationEventKey { get; set; }

    public string? NotificationEventName { get; set; }

    public string? Description { get; set; }

    public bool? UseEmailNotification { get; set; }

    public bool? UseInAppNotification { get; set; }

    public int? OptimisticLockField { get; set; }

    public int? Gcrecord { get; set; }
}