// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TestVCE.Models;

public partial class NotificationConfiguration
{
    public int Oid { get; set; }

    public string? NotificationEventKey { get; set; }

    public string? Description { get; set; }

    public bool? UseEmailNotificiation { get; set; }

    public bool? UseInAppNotificiation { get; set; }

    public int? OptimisticLockField { get; set; }

    public int? Gcrecord { get; set; }
}