// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TestVCE.Models;

public partial class Party
{
    public Guid Oid { get; set; }

    public byte[]? Photo { get; set; }

    public Guid? Address1 { get; set; }

    public Guid? Address2 { get; set; }

    public int? OptimisticLockField { get; set; }

    public int? Gcrecord { get; set; }

    public int? ObjectType { get; set; }

    public virtual Address? Address1Navigation { get; set; }

    public virtual Address? Address2Navigation { get; set; }

    public virtual XpobjectType? ObjectTypeNavigation { get; set; }

    public virtual Organization? Organization { get; set; }

    public virtual Person? Person { get; set; }

    public virtual ICollection<PhoneNumber> PhoneNumbers { get; set; } = new List<PhoneNumber>();

    public virtual ICollection<Task> Tasks { get; set; } = new List<Task>();
}