// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TestVCE.Models;

public partial class PermissionPolicyUserUsersPermissionPolicyRoleRole
{
    public Guid? Roles { get; set; }

    public Guid? Users { get; set; }

    public Guid Oid { get; set; }

    public int? OptimisticLockField { get; set; }

    public virtual PermissionPolicyRole? RolesNavigation { get; set; }

    public virtual PermissionPolicyUser? UsersNavigation { get; set; }
}