// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TestVCE.Models;

public partial class PermissionPolicyRole
{
    public Guid Oid { get; set; }

    public string? Name { get; set; }

    public bool? IsAdministrative { get; set; }

    public bool? CanEditModel { get; set; }

    public int? PermissionPolicy { get; set; }

    public int? OptimisticLockField { get; set; }

    public int? Gcrecord { get; set; }

    public int? ObjectType { get; set; }

    public virtual ApplicationRole? ApplicationRole { get; set; }

    public virtual XpobjectType? ObjectTypeNavigation { get; set; }

    public virtual ICollection<PermissionPolicyActionPermissionObject> PermissionPolicyActionPermissionObjects { get; set; } = new List<PermissionPolicyActionPermissionObject>();

    public virtual ICollection<PermissionPolicyNavigationPermissionsObject> PermissionPolicyNavigationPermissionsObjects { get; set; } = new List<PermissionPolicyNavigationPermissionsObject>();

    public virtual ICollection<PermissionPolicyTypePermissionsObject> PermissionPolicyTypePermissionsObjects { get; set; } = new List<PermissionPolicyTypePermissionsObject>();

    public virtual ICollection<PermissionPolicyUserUsersPermissionPolicyRoleRole> PermissionPolicyUserUsersPermissionPolicyRoleRoles { get; set; } = new List<PermissionPolicyUserUsersPermissionPolicyRoleRole>();
}