// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TestVCE.Models;

public partial class Person
{
    public Guid Oid { get; set; }

    public string? FirstName { get; set; }

    public string? LastName { get; set; }

    public string? MiddleName { get; set; }

    public DateTime? Birthday { get; set; }

    public string? Email { get; set; }

    public virtual Party OidNavigation { get; set; } = null!;
}