// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TestVCE.Models;

public partial class PropertyBagDescriptor
{
    public Guid Oid { get; set; }

    public int? OptimisticLockField { get; set; }

    public int? Gcrecord { get; set; }

    public virtual ICollection<PropertyDescriptorPropertyDescriptorsPropertyBagDescr3ef9c1ed> PropertyDescriptorPropertyDescriptorsPropertyBagDescr3ef9c1eds { get; set; } = new List<PropertyDescriptorPropertyDescriptorsPropertyBagDescr3ef9c1ed>();
}