// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TestVCE.Models;

public partial class PropertyDescriptor
{
    public Guid Oid { get; set; }

    public string? Code { get; set; }

    public string? Name { get; set; }

    public string? Description { get; set; }

    public string? Type { get; set; }

    public int? OptimisticLockField { get; set; }

    public int? Gcrecord { get; set; }

    public virtual ICollection<PropertyDescriptorPropertyDescriptorsPropertyBagDescr3ef9c1ed> PropertyDescriptorPropertyDescriptorsPropertyBagDescr3ef9c1eds { get; set; } = new List<PropertyDescriptorPropertyDescriptorsPropertyBagDescr3ef9c1ed>();

    public virtual ICollection<PropertyValue> PropertyValues { get; set; } = new List<PropertyValue>();
}