// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TestVCE.Models;

public partial class PropertyDescriptorPropertyDescriptorsPropertyBagDescr3ef9c1ed
{
    public Guid? PropertyBags { get; set; }

    public Guid? PropertyDescriptors { get; set; }

    public Guid Oid { get; set; }

    public int? OptimisticLockField { get; set; }

    public virtual PropertyBagDescriptor? PropertyBagsNavigation { get; set; }

    public virtual PropertyDescriptor? PropertyDescriptorsNavigation { get; set; }
}