// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TestVCE.Models;

public partial class Province
{
    public int Oid { get; set; }

    public string? ProvinceId { get; set; }

    public string? ProvinceThai { get; set; }

    public string? ProvinceEng { get; set; }

    public string? RegionAsFormal { get; set; }

    public string? RegionAsCommon { get; set; }

    public string? RegionAsVec { get; set; }

    public string? ProvinceType { get; set; }

    public int? OptimisticLockField { get; set; }

    public int? Gcrecord { get; set; }

    public virtual ICollection<Corporate> Corporates { get; set; } = new List<Corporate>();

    public virtual ICollection<District> Districts { get; set; } = new List<District>();

    public virtual ICollection<EmployerProfile> EmployerProfiles { get; set; } = new List<EmployerProfile>();

    public virtual ICollection<JobPosting> JobPostings { get; set; } = new List<JobPosting>();

    public virtual ICollection<Student> Students { get; set; } = new List<Student>();
}