// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TestVCE.Models;

public partial class Religion
{
    public int Oid { get; set; }

    public string? ReligionId { get; set; }

    public string? ReligionTh { get; set; }

    public string? ReligionEng { get; set; }

    public int? OptimisticLockField { get; set; }

    public int? Gcrecord { get; set; }

    public virtual ICollection<Student> Students { get; set; } = new List<Student>();
}