// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TestVCE.Models;

public partial class Resource
{
    public Guid Oid { get; set; }

    public string? Caption { get; set; }

    public int? Color { get; set; }

    public int? OptimisticLockField { get; set; }

    public int? Gcrecord { get; set; }

    public virtual ICollection<ResourceResourcesEventEvent> ResourceResourcesEventEvents { get; set; } = new List<ResourceResourcesEventEvent>();
}