// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TestVCE.Models;

public partial class RichTextMailMergeDatum
{
    public Guid Oid { get; set; }

    public string? Name { get; set; }

    public string? DataType { get; set; }

    public byte[]? Template { get; set; }

    public int? OptimisticLockField { get; set; }

    public int? Gcrecord { get; set; }
}