// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TestVCE.Models;

public partial class SalaryRange
{
    public int Oid { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? LastUpdatedDate { get; set; }

    public DateTime? DeletedDate { get; set; }

    public int? Order { get; set; }

    public string? SalaryRange1 { get; set; }

    public int? OptimisticLockField { get; set; }

    public int? Gcrecord { get; set; }

    public virtual ICollection<StudentJobRecord> StudentJobRecords { get; set; } = new List<StudentJobRecord>();
}