// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TestVCE.Models;

public partial class SchoolEmployee
{
    public int Oid { get; set; }

    public int? School { get; set; }

    public string? SchoolId { get; set; }

    public int? EmployeeTypeId { get; set; }

    public int? SchoolEmployeeType { get; set; }

    public string? Prefix { get; set; }

    public string? FirstName { get; set; }

    public string? LastName { get; set; }

    public string? IdCard { get; set; }

    public string? Phone { get; set; }

    public string? HouseNo { get; set; }

    public string? Moo { get; set; }

    public string? Trok { get; set; }

    public string? Soi { get; set; }

    public string? StartDate { get; set; }

    public string? Street { get; set; }

    public string? TumbolCode { get; set; }

    public string? Zipcode { get; set; }

    public string? TeachSubjectId { get; set; }

    public int? OptimisticLockField { get; set; }

    public int? Gcrecord { get; set; }

    public virtual SchoolEmployeeType? SchoolEmployeeTypeNavigation { get; set; }

    public virtual School? SchoolNavigation { get; set; }
}