// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TestVCE.Models;

public partial class SchoolEmployeeProfile
{
    public int Oid { get; set; }

    public Guid? ApplicationUser { get; set; }

    public string? Titlenameid { get; set; }

    public string? Name { get; set; }

    public string? Lastname { get; set; }

    public int? Gender { get; set; }

    public DateTime? DateOfBirth { get; set; }

    public string? Position { get; set; }

    public string? Email { get; set; }

    public string? PhoneNumber { get; set; }

    public string? IdCard { get; set; }

    public string? UserPhotoBase64String { get; set; }

    public int? OptimisticLockField { get; set; }

    public int? Gcrecord { get; set; }

    public virtual ApplicationUser? ApplicationUserNavigation { get; set; }

    public virtual ICollection<GraduatedStudentJobTrackingReport> GraduatedStudentJobTrackingReportSenderToCompleteNavigations { get; set; } = new List<GraduatedStudentJobTrackingReport>();

    public virtual ICollection<GraduatedStudentJobTrackingReport> GraduatedStudentJobTrackingReportSenderToConfirmNavigations { get; set; } = new List<GraduatedStudentJobTrackingReport>();
}