// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TestVCE.Models;

public partial class State
{
    public Guid Oid { get; set; }

    public string? ShortName { get; set; }

    public string? LongName { get; set; }

    public int? OptimisticLockField { get; set; }

    public int? Gcrecord { get; set; }
}