// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TestVCE.Models;

public partial class StudentStudyRecord
{
    public int Oid { get; set; }

    public int? Student { get; set; }

    public string? GraduatedYear { get; set; }

    public int? EducationalQualification { get; set; }

    public string? SchoolName { get; set; }

    public string? MajorNameTh { get; set; }

    public string? MinorNameTh { get; set; }

    public string? Gpa { get; set; }

    public int? OptimisticLockField { get; set; }

    public int? Gcrecord { get; set; }

    public virtual EducationalQualification? EducationalQualificationNavigation { get; set; }

    public virtual Student? StudentNavigation { get; set; }
}