// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TestVCE.Models;

public partial class Student
{
    public int Oid { get; set; }

    public Guid? ApplicationUser { get; set; }

    public string? SchoolId { get; set; }

    public string? StudentId { get; set; }

    public int? TitleName { get; set; }

    public string? Idcard { get; set; }

    public string? Firstname { get; set; }

    public string? Surname { get; set; }

    public string? SchoolName { get; set; }

    public string? StudentCode { get; set; }

    public string? Middlename { get; set; }

    public string? Gender { get; set; }

    public string? FirstnameEn { get; set; }

    public string? SurnameEn { get; set; }

    public string? Nickname { get; set; }

    public DateTime? Birthday { get; set; }

    public string? NationalityId { get; set; }

    public int? Nationality { get; set; }

    public string? RaceId { get; set; }

    public string? ReligionId { get; set; }

    public int? Religion { get; set; }

    public string? Tel { get; set; }

    public string? Fax { get; set; }

    public string? Email { get; set; }

    public string? GroupCode { get; set; }

    public string? GroupName { get; set; }

    public string? GroupAbbr { get; set; }

    public string? GradeNameTh { get; set; }

    public int? CertificateType { get; set; }

    public DateTime? EntranceDate { get; set; }

    public string? EntranceYear { get; set; }

    public string? EntranceSemester { get; set; }

    public string? GradeId { get; set; }

    public string? GraduateCode { get; set; }

    public string? HouseId { get; set; }

    public string? HouseNumber { get; set; }

    public string? Moo { get; set; }

    public string? Soi { get; set; }

    public string? Street { get; set; }

    public string? TumbolCode { get; set; }

    public int? Province { get; set; }

    public int? District { get; set; }

    public int? Tambon { get; set; }

    public string? ZipCode { get; set; }

    public int? Major { get; set; }

    public string? MajorId { get; set; }

    public string? MajorCode { get; set; }

    public string? MajorNameTh { get; set; }

    public int? Minor { get; set; }

    public string? MinorId { get; set; }

    public string? MinorCode { get; set; }

    public string? MinorNameTh { get; set; }

    public string? BloodName { get; set; }

    public string? ParentPrefixId { get; set; }

    public string? ParentFirstname { get; set; }

    public string? ParentSurname { get; set; }

    public string? ParentRelation { get; set; }

    public string? ParentPhone { get; set; }

    public string? Gpax { get; set; }

    public string? StudentStatusCode { get; set; }

    public string? StudentStatusName { get; set; }

    public string? StudentTypeCode { get; set; }

    public string? StudentTypeName { get; set; }

    public string? Base64thrumnail { get; set; }

    public string? TitlenameId { get; set; }

    public int? Marital { get; set; }

    public string? Hight { get; set; }

    public string? Weight { get; set; }

    public string? Domicile { get; set; }

    public int? Military { get; set; }

    public string? Contacthousenumber { get; set; }

    public string? Contactsoi { get; set; }

    public string? Contactmoo { get; set; }

    public string? Contactstreet { get; set; }

    public int? Contacttambon { get; set; }

    public string? GraduatedYearTh { get; set; }

    public string? GraduatedSemeter { get; set; }

    public int? CompletionPercentage { get; set; }

    public DateTime? ImportDataDate { get; set; }

    public int? LookingForJob { get; set; }

    public int? OptimisticLockField { get; set; }

    public int? Gcrecord { get; set; }

    public DateTime? ProfileUpdatedDate { get; set; }

    public bool? IsProfileUpdated { get; set; }

    public DateTime? LastImportDate { get; set; }

    public bool? IsInImportingProcess { get; set; }

    public virtual ApplicationUser? ApplicationUserNavigation { get; set; }

    public virtual CertificateType? CertificateTypeNavigation { get; set; }

    public virtual Tambon? ContacttambonNavigation { get; set; }

    public virtual District? DistrictNavigation { get; set; }

    public virtual ICollection<GraduatedStudentJobTrackingReportStudentDetail> GraduatedStudentJobTrackingReportStudentDetails { get; set; } = new List<GraduatedStudentJobTrackingReportStudentDetail>();

    public virtual ICollection<JobApplication> JobApplications { get; set; } = new List<JobApplication>();

    public virtual LookingForJob? LookingForJobNavigation { get; set; }

    public virtual Major? MajorNavigation { get; set; }

    public virtual Minor? MinorNavigation { get; set; }

    public virtual Nationality? NationalityNavigation { get; set; }

    public virtual ICollection<PostLookingForJob> PostLookingForJobs { get; set; } = new List<PostLookingForJob>();

    public virtual Province? ProvinceNavigation { get; set; }

    public virtual Religion? ReligionNavigation { get; set; }

    public virtual ICollection<StudentJobRecord> StudentJobRecords { get; set; } = new List<StudentJobRecord>();

    public virtual ICollection<StudentResume> StudentResumes { get; set; } = new List<StudentResume>();

    public virtual ICollection<StudentReward> StudentRewards { get; set; } = new List<StudentReward>();

    public virtual ICollection<StudentStudyRecord> StudentStudyRecords { get; set; } = new List<StudentStudyRecord>();

    public virtual ICollection<StudentVeceducationInformation> StudentVeceducationInformations { get; set; } = new List<StudentVeceducationInformation>();

    public virtual Tambon? TambonNavigation { get; set; }

    public virtual TitleName? TitleNameNavigation { get; set; }
}