// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TestVCE.Models;

public partial class StudentJobRecord
{
    public int Oid { get; set; }

    public int? Student { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public int? OrganizationType { get; set; }

    public string? OrganizationName { get; set; }

    public string? PositionName { get; set; }

    public string? JobDescription { get; set; }

    public int? SalaryRange { get; set; }

    public decimal? Salary { get; set; }

    public int? RelatedWithGraudatedFieldStatus { get; set; }

    public int? OptimisticLockField { get; set; }

    public int? Gcrecord { get; set; }

    public virtual OrganizationType? OrganizationTypeNavigation { get; set; }

    public virtual SalaryRange? SalaryRangeNavigation { get; set; }

    public virtual Student? StudentNavigation { get; set; }
}