// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TestVCE.Models;

public partial class SubjectType
{
    public int Oid { get; set; }

    public string? SubjectTypeCode { get; set; }

    public string? SubjectTypeId { get; set; }

    public string? SubjectTypeNameEn { get; set; }

    public string? SubjectTypeNameTh { get; set; }

    public int? OptimisticLockField { get; set; }

    public int? Gcrecord { get; set; }
}