// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TestVCE.Models;

public partial class Tambon
{
    public int Oid { get; set; }

    public int? District { get; set; }

    public string? TambonId { get; set; }

    public string? TambonThai { get; set; }

    public string? TambonEng { get; set; }

    public string? TambonThaiShort { get; set; }

    public string? TambonEngShort { get; set; }

    public string? PostCodeMain { get; set; }

    public string? PostCodeAll { get; set; }

    public string? PostCodeRemark { get; set; }

    public string? DistrictId { get; set; }

    public int? OptimisticLockField { get; set; }

    public int? Gcrecord { get; set; }

    public virtual District? DistrictNavigation { get; set; }

    public virtual ICollection<EmployerProfile> EmployerProfiles { get; set; } = new List<EmployerProfile>();

    public virtual ICollection<JobPosting> JobPostings { get; set; } = new List<JobPosting>();

    public virtual ICollection<School> Schools { get; set; } = new List<School>();

    public virtual ICollection<Student> StudentContacttambonNavigations { get; set; } = new List<Student>();

    public virtual ICollection<Student> StudentTambonNavigations { get; set; } = new List<Student>();
}