// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TestVCE.Models;

public partial class TitleName
{
    public int Oid { get; set; }

    public string? TitleNameId { get; set; }

    public string? TitleNameTh { get; set; }

    public string? TitleNameEng { get; set; }

    public int? OptimisticLockField { get; set; }

    public int? Gcrecord { get; set; }

    public virtual ICollection<EmployerProfile> EmployerProfiles { get; set; } = new List<EmployerProfile>();

    public virtual ICollection<Student> Students { get; set; } = new List<Student>();

    public virtual ICollection<VerifyManager> VerifyManagers { get; set; } = new List<VerifyManager>();
}