// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TestVCE.Models;

public partial class UserBookmark
{
    public int Oid { get; set; }

    public string? UserType { get; set; }

    public string? UserReferenceKey { get; set; }

    public string? BookmarkTypeName { get; set; }

    public string? BookmarkValue { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? OptimisticLockField { get; set; }

    public int? Gcrecord { get; set; }
}