// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TestVCE.Models;

public partial class ViewCounter
{
    public int Oid { get; set; }

    public int? Counter { get; set; }

    public string? ReferenceEntityOid { get; set; }

    public string? ReferenceEntityClassName { get; set; }

    public int? OptimisticLockField { get; set; }

    public int? Gcrecord { get; set; }
}