// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TestVCE.Models;

public partial class XpoInstanceKey
{
    public int Oid { get; set; }

    public Guid? KeyId { get; set; }

    public Guid? InstanceId { get; set; }

    public string? Properties { get; set; }

    public int? OptimisticLockField { get; set; }

    public int? Gcrecord { get; set; }
}