// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TestVCE.Models;

public partial class XpoState
{
    public Guid Oid { get; set; }

    public string? Caption { get; set; }

    public Guid? StateMachine { get; set; }

    public string? MarkerValue { get; set; }

    public string? TargetObjectCriteria { get; set; }

    public int? OptimisticLockField { get; set; }

    public int? Gcrecord { get; set; }

    public virtual XpoStateMachine? StateMachineNavigation { get; set; }

    public virtual ICollection<XpoStateAppearance> XpoStateAppearances { get; set; } = new List<XpoStateAppearance>();

    public virtual ICollection<XpoStateMachine> XpoStateMachines { get; set; } = new List<XpoStateMachine>();

    public virtual ICollection<XpoTransition> XpoTransitionSourceStateNavigations { get; set; } = new List<XpoTransition>();

    public virtual ICollection<XpoTransition> XpoTransitionTargetStateNavigations { get; set; } = new List<XpoTransition>();
}