// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TestVCE.Models;

public partial class XpweakReference
{
    public Guid Oid { get; set; }

    public int? TargetType { get; set; }

    public string? TargetKey { get; set; }

    public int? OptimisticLockField { get; set; }

    public int? Gcrecord { get; set; }

    public int? ObjectType { get; set; }

    public virtual ICollection<AuditDataItemPersistent> AuditDataItemPersistentNewObjectNavigations { get; set; } = new List<AuditDataItemPersistent>();

    public virtual ICollection<AuditDataItemPersistent> AuditDataItemPersistentOldObjectNavigations { get; set; } = new List<AuditDataItemPersistent>();

    public virtual AuditedObjectWeakReference? AuditedObjectWeakReference { get; set; }

    public virtual XpobjectType? ObjectTypeNavigation { get; set; }

    public virtual ICollection<PropertyValue> PropertyValues { get; set; } = new List<PropertyValue>();

    public virtual XpobjectType? TargetTypeNavigation { get; set; }
}